dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: tJMrrbtIyDu6/nqiIcTfACaC6i2IM+iIh2qhBa0dkQRX43Yeq3bHg8KDcIUfpg8L27RnTO1BBEsjl487JCpuBPi4i8z8yXeCTSWbz/GVBAs3fWiE90znAuWlZWOH+b5lklW8mgAkG+UZssLCluODINmB1uwLH+tMfziqFGlmHsjXOPHV/hCscjY0Sl8UR4E47liLefHNvuy0o9DVA1CNK61BDtBAhb5G7gpES2WWdfG3iCHngXLX2/dzqB/8RK+opUOE5Y16GVVFEvoYoEhXwzlnRKems0dA+aWK7hX5uhnELDBhU0qBhiR6eiNwrqOBL/g/ZK7ApYiUrYBH4ztd4YbBT3Bx9G2OnvWt81k4FyA1GGeNgF9OyjVgkwk9K2yo+1RmJRjsQdw9TBinGcFzIG7TNeuAk4qYrtTShD3V9zV2l16d0cRg6rESDXoCytAoA8/ICK8RfXp23laQ8ZG7Fijjt9ZPP19CSuZ4zfBrRLwSRudwrgNhJB4wtORXLhwZNXernY67ZjyXfZSPVEK1P/xWUbJQYO+ANfuAswmW9Y4dygUbnel++HaNixU7QErpmuppAn5nEr2cVmEL+YBkdgAX2luTTTOyBeXId1nhM1Hpxdtv1auF/H+LeFl+FqX7cHeYIsAs621opk5gMfGu98xlSWML0uJV6tbAZBqdSag=
