dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: TtLNuqRYXs/quvV54aFT5b9peghEEnEVpPTnK1crpT2P9m3baZwagrhwuibxEt0a9MufEojOpkrlqNm/xQJ0Gp72xyAC7SVGQ7MbPYcajoUmbe+tZ8TZWqGUtkimMcPix2qsjiCAFniq5iG8RAs4GfidXgqN2vyd/ZyhtZxJrsXDvAorzOsaCdOe5EcQUJnbUBPX2ctOGsa5ZT+blNpku3QJj9NjLSYeG/28bAJ66oTg/sWbqmzbvk0VaP1td8cXtdeO6xEaPUJJhUAwHPhb1+5N/4oqXHE9GbSTI/hBycDwqJtM76ltBnXixJzr36QL62o34fvZKjk+d+hg8MNsI1aQakCyDcC/GjF/f3QmECYX25J5kFW3drveQAEZDFK7B4N1Q/EsoemFps5arO6nX0LA7ISCePO61SAAcd8WlBZli9oKKbKG1RfrgoGAUDuPXlOWlgs02glgFqFlOayVCLAirhdviegANqb9jf/0JMi6uDpADKFHQ54j0lfaVHAXKReFEFi07p26fOkBo+/zbLFFd6ArZuxID2qbGovvAq38ggpOeBe8ko4rhNkZg+bJWCSqMku8yyOibqRyr8LErT/BqiUwID24bJenNr6wagzknMtGwrt+nvSO0D8hz/WQ8w06PLf4zDgSDXJcLBZQLe98pBLMPLgN1hLpWnpldek=
